# Database Configuration Properties
db.url=jdbc:mysql://127.0.0.1:3306/jobnest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=Krishna1931@
db.driver=com.mysql.cj.jdbc.Driver
